TaskManagmentWithRazorPages/Pages/Duties/Comment.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Domain.Entities;
using Domain.Enums;
using Domain.Interfaces.Repository;

using Microsoft.AspNetCore.Mvc.ViewFeatures;
using TaskManagmentWithRazorPages.Pages.Duties.ViewModels;
namespace TaskManagmentWithRazorPages.Pages.Duties
{
    public class CommentModel : PageModel
    {
        ICommentRepository _commentRepository;

        public Comment _comment;

        public CommentModel(ICommentRepository commentRepository)
        {
            _commentRepository = commentRepository;
          

        }

        public async Task OnGet(int commentId)        {
          
            _comment = await _commentRepository.GetByIdAsync(commentId);

        }
        
    }
}

TaskManagmentWithRazorPages/Pages/Duties/Detail.cshtml.cs
using Domain.Entities;
using Domain.Enums;
using Domain.Interfaces.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using TaskManagmentWithRazorPages.Pages.Duties.ViewModels;

namespace TaskManagmentWithRazorPages.Pages.Duties
{
    public class DetailModel : PageModel
    {
        ICommentRepository _commentRepository;
        IDutyRepository _dutyRepository;
        public IList<Comment> _comments;
        public Duty _duty;
        public Comment _comment;

        public DetailModel(ICommentRepository commentRepository, IDutyRepository dutyRepository)
        {
            _commentRepository = commentRepository;
            _dutyRepository = dutyRepository;

        }

        public async Task OnGet(int dutyId)
        {
            _duty = await _dutyRepository.GetByIdAsync(dutyId);
            _comments = await _commentRepository.GetAllByIdAsync(dutyId);


        }

        public PartialViewResult OnGetAddCommentPartial(int dutyId)
        {
            VMComment vmComment = new VMComment()
            {
                DutyId = dutyId
            };

            return new PartialViewResult
            {
                ViewName = "_AddComment",
                ViewData = new ViewDataDictionary<VMComment>(ViewData, vmComment)
            };
        }
        public async Task<IActionResult> OnPostAddComment(VMComment vmComment)
        {
            if (vmComment != null)
            {
                Comment comment = new Comment()
                {

                    DutyId = vmComment.DutyId,
                    CommentText = vmComment.CommentText,
                    AddedDate = DateTime.Now,
                    ReminderDate = vmComment.ReminderDate,
                    Type = (CommentType)vmComment.Type,


                };
                if (vmComment.Id != 0)
                {
                    comment.Id = vmComment.Id;
                    _commentRepository.UpdateAsync(comment);
                }

                else
                    _commentRepository.AddAsync(comment);
            }



            return RedirectToPage(new { dutyId = vmComment.DutyId });
        }
        public async Task<PartialViewResult> OnGetUpdateCommentPartial(int Id)
        {
            var comment = await _commentRepository.GetByIdAsync(Id);

            VMComment vmComment = new VMComment()
            {
                Id = comment.Id,
                AddedDate = comment.AddedDate,
                ReminderDate = comment.ReminderDate,
                CommentText = comment.CommentText,
                DutyId = comment.DutyId,
                Type = (int)comment.Type
            };
            return new PartialViewResult
            {
                ViewName = "_AddComment",
                ViewData = new ViewDataDictionary<VMComment>(ViewData, vmComment)
            };
        }
        public async Task<IActionResult> OnGetDeleteComment(int Id, int dutyId)
        {
            await _commentRepository.DeleteAsync(Id);
            return RedirectToPage(new { dutyId = dutyId });
        }
        public async Task<JsonResult> OnGetSearch(string searchText,int dutyId)
        {
            Dictionary<string, string> commentsList = new Dictionary<string, string>();
            var comments = await _commentRepository.GetAllBySearchTextAsync(searchText, dutyId);

            foreach (var comment in comments)
            {
                commentsList.Add(comment.Id.ToString(), comment.CommentText);
            }
            return new JsonResult(commentsList);

        }


    }
}

TaskManagmentWithRazorPages/Pages/Duties/Index.cshtml.cs
using Domain.Entities;
using Domain.Enums;
using Domain.Interfaces.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using TaskManagmentWithRazorPages.Pages.Duties.ViewModels;

namespace TaskManagmentWithRazorPages.Pages.Duties
{
    public class IndexModel : PageModel
    {
        IDutyRepository _dutyRepository;
        public IList<Duty> _duties;
        public IndexModel(IDutyRepository dutyRepository)
        {
            _dutyRepository = dutyRepository;
        }

        public async Task OnGetAsync()
        {
            _duties = await _dutyRepository.GetAllAsync();

        }

        public PartialViewResult OnGetAddDutyPartial()
        {
            VMDuty vmduty = new VMDuty();
          
            return new PartialViewResult
            {
                ViewName = "_AddDuty",
                ViewData = new ViewDataDictionary<VMDuty>(ViewData,  vmduty)
            };
        }

        public async Task<IActionResult> OnPostAddDuty(VMDuty vmduty)
        {
            if (vmduty.Title != null && vmduty.Description!=null)
            {


                Duty NewDuty = new Duty()
                {
                    Title = vmduty.Title,
                    Description = vmduty.Description,
                    CreatedDate = DateTime.Now,
                    NextActionDate = vmduty.NextActionDate,
                    RequiredBy = vmduty.RequiredBy,
                    Type = (DutyType)vmduty.Type,
                    Status = (DutyStatus)vmduty.Status,

                };

                _dutyRepository.AddAsync(NewDuty);
            }
            return RedirectToPage();
        }
    }
}

TaskManagmentWithRazorPages/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace TaskManagmentWithRazorPages.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TaskManagmentWithRazorPages/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TaskManagmentWithRazorPages.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> OnGet()
        {
            return RedirectToPage("Duties/Index");

        }
    }
}

TaskManagmentWithRazorPages/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TaskManagmentWithRazorPages.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TaskManagmentWithRazorPages/Pages/Duties/Comment.cshtml
@page
@model TaskManagmentWithRazorPages.Pages.Duties.CommentModel
@{
}
<div id="modal-placeholder"></div>
<div class="container mt-5">

    <div class="row d-flex justify-content-center ">

        <div class="col-md-6">

            <div class="card">

                <div class="input-box">



                    <div id="content">

                        <div class="list">

                            <i class="fa fa-fire"></i>
                            <div class="d-flex justify-content-center py-2">
                                <div class="second py-2 px-2">

                                    <div class="d-flex justify-content-between py-1 pt-2">
                                        <div><span class="text2">UserName</span></div>
                                        <div><span class="text3">@Model._comment.AddedDate</span><span class="thumbup"><i class="fa fa-thumbs-o-up"></i></span></div>
                                    </div>

                                    <div>
                                        <span class="text1">@Model._comment.CommentText </span>
                                    </div>


                                    <div class="d-flex justify-content-center pt-3 pb-2">
                                        <button class="btn btn-info" type="button" data-toggle="addComment-modal" data-url=@Url.Page("Detail", "UpdateCommentPartial",new {Id=@Model._comment.Id})>Edit</button>
                                        <a href=@Url.Page("Detail", "DeleteComment",new {Id=@Model._comment.Id,dutyId=@Model._comment.DutyId}) class="btn btn-secondary active">Delete</a>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>
</div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
<script>

    $(function() {

        var placeholderElement = $('#modal-placeholder');
        $('button[data-toggle="addComment-modal"]').click(function(event) {
            var url = $(this).data('url');
            $.get(url).done(function(data) {
                placeholderElement.html(data);
                placeholderElement.find('.modal').modal('show');
            });
        });

    });



</script>

TaskManagmentWithRazorPages/Pages/Duties/Detail.cshtml
@page
@model TaskManagmentWithRazorPages.Pages.Duties.DetailModel
@{
}

<div id="modal-placeholder"></div>


<h2> @Model._duty.Title</h2>
<h4>@Model._duty.Description</h4>

<input hidden id="dutyId" value="@Model._duty.Id"/>

<div class="container mt-5">
    <div class="d-flex justify-content-center pt-3 pb-2">

        <button class="btn btn-success form-control addtxt" type="button" data-toggle="addComment-modal" data-url=@Url.Page("Detail", "AddCommentPartial",new {dutyId=Model._duty.Id})><i class="fa fa-filter"><span class="fontbtn px-2">+ Add a comment</span></i></button>
    </div>
    <div class="row d-flex justify-content-center ">

        <div class="col-md-12">

            <div class="card">

                <div class="input-box">
                    <input id="searchBox" type="text" class="form-control" placeholder="search">
                    <i class="fa fa-search"></i>

                    <div class="col-md-12">

                        <div id="searchResultDiv">
                            <ul id="list">
                            </ul>
                        </div>
                    </div>


                    <div id="content">
                        @if (Model._comments.Any())
                        {
                            @foreach (var comment in Model._comments)
                            {
                                <div class="list">

                                    <i class="fa fa-fire"></i>
                                    <div class="d-flex justify-content-center py-2">
                                        <div class="second py-2 px-2">

                                            <div class="d-flex justify-content-between py-1 pt-2">
                                                <div><span class="text2">UserName</span></div>
                                                <div><span class="text3">@comment.AddedDate</span><span class="thumbup"><i class="fa fa-thumbs-o-up"></i></span></div>
                                            </div>

                                            <div>
                                                <span class="text1">@comment.CommentText </span>
                                            </div>


                                            <div class="d-flex justify-content-center pt-3 pb-2">
                                                <button class="btn btn-info" type="button" data-toggle="addComment-modal" data-url=@Url.Page("Detail", "UpdateCommentPartial",new {Id=comment.Id})>Edit</button>
                                                <a href=@Url.Page("Detail", "DeleteComment",new {Id=comment.Id,dutyId=comment.DutyId}) class="btn btn-secondary active">Delete</a>
                                            </div>

                                        </div>
                                    </div>
                                </div>



                            }

                        }



                    </div>






                </div>

            </div>

        </div>

    </div>
</div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script>
        $(function() {

            var placeholderElement = $('#modal-placeholder');
            $('button[data-toggle="addComment-modal"]').click(function(event) {
                var url = $(this).data('url');
                $.get(url).done(function(data) {
                    placeholderElement.html(data);
                    placeholderElement.find('.modal').modal('show');
                });
            });

        });
                                                           


    </script>

    <script>
        $(document).ready(function() {
            $("#searchBox").on("keyup", function() {

                var value = $(this).val().toLowerCase();
                var dutyId = $("#dutyId").val();
                if (value != '')
                {
                    document.getElementById("list").innerHTML = "";
                  
                    //var commentId = $("").val();
                    //document.getElementById("content").style.display = "inline";
                    var url = "../Duties/Detail?handler=Search&searchText=" + value+"&dutyId="+dutyId;
                    document.getElementById("list").innerHTML = "";
                    var ul = document.getElementById("list");
                    $.get(url).done(function(data) {
                        for (var d in data) {

                            if (data.hasOwnProperty(d)) {
                                
                                url = "../Duties/Comment?handler=Get&commentId="+ d;
                                 $("#list").append('<li ><a href='+url+'>' + data[d] + '</a></li>')

                            }
                            else {

                                document.getElementById("list").innerHTML = "";
                                document.getElementById("content").style.display = "none";
                            }

                        }

                    });
                }

                else 
                {
                   
                    document.getElementById("list").innerHTML = "";
                    document.getElementById("content").style.display = "inline";
                }


            });
        });
    </script>

    <script>
        function onSelect(e) {
            var dataItem = this.dataItem(e.item);
            alert(dataItem);
        }
    </script>

    <style>
        /*    body{
                                                                                                        background-color: #fff;
                                                                                                    }*/
        .container {
            /*background-color: #eef2f5;*/
            width: 400px;
        }

        .addtxt {
            padding-top: 10px;
            padding-bottom: 10px;
            text-align: center;
            font-size: 13px;
            width: 350px;
            background-color: #eeeeee69;
            font-weight: 500;
        }

        /*  .form-control: focus {
                                                                                    color: #000;
                                                                                }*/

        .second {
            width: 350px;
            background-color: white;
            border-radius: 4px;
            box-shadow: 10px 10px 5px #aaaaaa;
        }

        .text1 {
            font-size: 13px;
            font-weight: 500;
            color: #56575b;
        }

        .text2 {
            font-size: 13px;
            font-weight: 500;
            margin-left: 6px;
            color: #56575b;
        }

        .text3 {
            font-size: 13px;
            font-weight: 500;
            margin-right: 4px;
            color: #828386;
        }

        .text3o {
            color: #00a5f4;
        }

        .text4 {
            font-size: 13px;
            font-weight: 500;
            color: #828386;
        }

        .text4i {
            color: #00a5f4;
        }

        .text4o {
            color: white;
        }

        .thumbup {
            font-size: 13px;
            font-weight: 500;
            margin-right: 5px;
        }

        .thumbupo {
            color: #17a2b8;
        }


        .card {
            background-color: #fff;
            padding: 15px;
            border: none;
        }

        .input-box {
            position: relative;
        }

            .input-box i {
                position: absolute;
                right: 13px;
                top: 15px;
                color: #ced4da;
            }

        .form-control {
            height: 50px;
            background-color: #eeeeee69;
        }

            .form-control:focus {
                background-color: #eeeeee69;
                box-shadow: none;
                border-color: #eee;
            }


        .list {
            padding-top: 20px;
            padding-bottom: 10px;
            display: flex;
            align-items: center;
        }

        .border-bottom {
            border-bottom: 2px solid #eee;
        }

        .list i {
            font-size: 19px;
            color: red;
        }

        .list small {
            color: #dedddd;
        }
    </style>

TaskManagmentWithRazorPages/Pages/Duties/Index.cshtml
@page
@model TaskManagmentWithRazorPages.Pages.Duties.IndexModel
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h4>Tasks</h4>
<div id="modal-placeholder"></div>

<button class="btn btn-success" type="button" data-toggle="addDuty-modal" data-url=@Url.Page("Index", "AddDutyPartial")><i class="fa fa-filter"><span class="fontbtn px-2">Add Task</span></i></button>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>


<table class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Created Date</th>
            <th scope="col">Task Status</th>
            <th scope="col">Task Type</th>
            @*<th scope="col">Assigned Users</th>*@
            <th scope="col">Next Action Date</th>
        </tr>
    </thead>
    @foreach (var task in Model._duties)
    {
        <tr>
            <td scope="col"><a href="@Url.Page("Detail","Get",new {dutyId=@task.Id})">@task.Title</a></td>
            <td scope="col">@task.Description</td>
            <td scope="col">@task.CreatedDate</td>
            <td scope="col">@task.Status</td>
            <td scope="col">@task.Type</td>
            @*<td scope="col">@task.</td>*@
            <td scope="col">@task.NextActionDate</td>
        </tr>
    }
</table>


<script>
    $(function() {
       
        var placeholderElement = $('#modal-placeholder');
        $(document).on('click', 'button[data-toggle="addDuty-modal"]', function(event) {
            var url = $(this).data('url');
            $.get(url).done(function(data) {
                placeholderElement.html(data);
                placeholderElement.find('.modal').modal('show');
            });
        });
        placeholderElement.on('click', '[data-save="modal"]', function(event) {
            event.preventDefault();
            var form = $(this).parents('.modal').find('form');
            var actionUrl = form.attr('action');
            var dataToSend = form.serialize();
            $.post(actionUrl, dataToSend).done(function(data) {
                placeholderElement.find('.modal').modal('hide');
                location.reload()
            });
        });
    });
</script>

TaskManagmentWithRazorPages/Pages/Duties/_AddComment.cshtml
@model ViewModels.VMComment


<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="AddForm" asp-page-handler="AddComment" method="post" asp-page="Detail" name="addComment-modal-form">
                    @Html.HiddenFor(m=>m.Id)
                    @Html.HiddenFor(m=>m.DutyId)

                    <div class="row form-group mb-4">
                        @Html.LabelFor(m=>m.CommentText)
                        @Html.EditorFor(m=>m.CommentText)
                    </div>


                    @Html.DropDownList("Type",
                    Html.GetEnumSelectList<Domain.Enums.CommentType>(),
                    "Select Comment Type")

                    <div class="row form-group mb-4">
                        @Html.LabelFor(m=>m.ReminderDate)
                        @Html.EditorFor(m=>m.ReminderDate)
                    </div>


                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" form="AddForm" class="btn btn-primary">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

TaskManagmentWithRazorPages/Pages/Duties/_AddDuty.cshtml
@model ViewModels.VMDuty
<div class="modal fade" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header headerStyle">
                <h5>Add Duty</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="AddForm" asp-page-handler="AddDuty" method="post" asp-page="Index" name="addDuty-modal-form">
                    <div class="row form-group mb-4">
                        @Html.LabelFor(m=>m.Title)
                        @Html.EditorFor(m=>m.Title)
                    </div>
                    <div class="row form-group mb-4">
                        @Html.LabelFor(m=>m.Description)
                        @Html.EditorFor(m=>m.Description)
                    </div>
                    <div class="row form-group mb-4">
                        @Html.LabelFor(m=>m.RequiredBy)
                        @Html.EditorFor(m=>m.RequiredBy)
                    </div>
                     <div class="row form-group mb-4">
                      
                    </div>
                    <div class="row form-group mb-4">
                        @Html.DropDownList("Status",
                        Html.GetEnumSelectList<Domain.Enums.DutyStatus>(),
                        "Select Status")
                    </div>
                    <div class="row form-group mb-4">

                        @Html.DropDownList("Type",
                        Html.GetEnumSelectList<Domain.Enums.DutyType>(),
                        "Select Type")
                    </div>
                    <div class="row form-group mb-4">
                        @Html.LabelFor(m=>m.NextActionDate)
                        @Html.EditorFor(m=>m.NextActionDate)
                    </div>

                </form>
            </div>
            <div style="position:sticky; bottom:0">
                <div class="modal-footer d-flex justify-content-center" >
                     <button type="submit" form="AddForm" class="btn btn-primary">Save changes</button>
                    <button type="button" class="btn cancelBtn" data-bs-dismiss="modal">Close</button>
                    @*<button type="button" class="btn submitBtn" data-save="modal">Kaydet</button>*@


                </div>
            </div>
        </div>
    </div>
</div>
@*<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <form id="AddForm" asp-page-handler="AddDuty" method="post" asp-page="Index" name="addDuty-modal-form">


                    <div class="row form-group mb-4">
                        @Html.LabelFor(m=>m.Title)
                        @Html.EditorFor(m=>m.Title)
                    </div>

                    <div class="row form-group mb-4">
                        @Html.LabelFor(m=>m.Description)
                        @Html.EditorFor(m=>m.Description)
                    </div>

                    <div class="row form-group mb-4">
                        @Html.LabelFor(m=>m.RequiredBy)
                        @Html.EditorFor(m=>m.RequiredBy)
                    </div>
                    <div class="row form-group mb-4">
                        @Html.LabelFor(m=>m.RequiredBy)
                        @Html.EditorFor(m=>m.RequiredBy)
                    </div>


                    <select asp-for="AssignedTo" asp-items="Html.GetEnumSelectList<Domain.Enums.UserList>()" multiple="multiple" ></select>



                    @Html.DropDownList("Status",
                    Html.GetEnumSelectList<Domain.Enums.DutyStatus>(),
                    "Select Status")

                    @Html.DropDownList("Type",
                    Html.GetEnumSelectList<Domain.Enums.DutyType>(),
                    "Select Type")


                    <div class="row form-group mb-4">
                        @Html.LabelFor(m=>m.NextActionDate)
                        @Html.EditorFor(m=>m.NextActionDate)
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" form="AddForm" class="btn btn-primary">Save changes</button>

                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>*@

TaskManagmentWithRazorPages/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TaskManagmentWithRazorPages/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagmentWithRazorPages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagmentWithRazorPages.styles.css" asp-append-version="true" />



</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">TaskManagmentWithRazorPages</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TaskManagmentWithRazorPages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>